### ISSUE TITLE
Missing rest button hole on case?

### ISSUE THREAD

**Issue by tangbonze** [achyudh/karma#1]
I can't find reset switch hole on case. Could you please check if you miss it?

I mod a bit to enable choc v2 switch but I also need to change hole in bottom case. Could you please kindly share bottom case step? That will make it more easy to mod.

Thanks.

**Comment by achyudh** [comment]
> I can't find reset switch hole on case. Could you please check if you miss it?

This is actually intentional. I didn't see the need for making a reset switch as there were a bunch of other options:
- Pressing the reset button on the XIAO BLE microcontroller 
- Shorting the reset pads on the PCB
- Mapping a key combination to reset in ZMK (this is what I normally use for flashing)

> Could you please kindly share bottom case step?

 Happy to share the step files! They have been added to https://github.com/achyudh/karma/tree/main/enclosure

**Comment by tangbonze** [comment]
Thank you and great design!
________________________________
发件人: Achyudh Ram ***@***.***>
发送时间: 2024年10月15日 9:56
收件人: achyudh/karma ***@***.***>
抄送: KeebNERD ***@***.***>; Author ***@***.***>
主题: Re: [achyudh/karma] Missing rest button hole on case? (Issue #1)


I can't find reset switch hole on case. Could you please check if you miss it?

This is actually intentional. I didn't see the need for making a reset switch as there were a bunch of other options:

  *   Pressing the reset button on the XIAO BLE microcontroller
  *   Shorting the reset pads on the PCB
  *   Mapping a key combination to reset in ZMK (this is what I normally use for flashing)

Could you please kindly share bottom case step?

Happy to share the step files! They have been added to https://github.com/achyudh/karma/tree/main/enclosure

―
